---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: ckk3478-test-redis
    username: ckk3478
    env: test
spec:
  type: ClusterIP
  selector:
    app: ckk3478-test-redis
  ports:
  - name: test-redis
    port: 5000
    targetPort: 5000