---
apiVersion: v1
kind: Pod
metadata:
  name: hello-name
  labels:
    greeting: "personalized"
spec:
  containers:
    - name: hello-name
      image: ubuntu:18.04
      env:
        - name: "NAME"
          value: "Cassandre"
      command: ['sh', '-c', 'echo "Hello, $(NAME)!" && sleep 3600']