---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-1deployment
  labels:
    app: ckk3478-1test-flask
    username: ckk3478
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckk3478-1test-flask
      username: ckk3478
      env: test
  template:
    metadata:
      labels:
        app: ckk3478-1test-flask
        username: ckk3478
        env: test
    spec:
      containers:
        - name: test-1flask
          imagePullPolicy: Always
          image: casskk/homework07:1.0
          command: ['python','api.py']
          env:
          - name: API_GREETING
            value: "Hello from api.py"
          ports:
          - name: http
            containerPort: 5000