---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r-ckk3478-data
  labels:
    app: ckk3478-redis-hw7
    username: ckk3478
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi