---
apiVersion: v1
kind: Service
metadata:
  name: r-service
  labels:
    app: ckk3478-redis-hw7
    username: ckk3478
    env: test1
spec:
  type: ClusterIP
  selector:
    app: ckk3478-redis-hw7
  ports:
  - name: test-redis1
    port: 6379
    targetPort: 6379